
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlmkdwuwkkvyjdpfsbzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsbWtkd3V3a2t2eWpkcGZzYnpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NzczMjQsImV4cCI6MjA2MzA1MzMyNH0.B3aUsPs-jeBUjoPBFBNqSdwuXfHVO1xA0UgWc0b-eaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
